[package]
name = "korekto"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-runtime = "0.24.0"
shuttle-axum = "0.24.0"
shuttle-static-folder = "0.24.0"
shuttle-secrets = "0.24.0"
axum = "0.6.20"
axum-extra = { version = "0.7.7", features = ["cookie-private", "cookie-key-expansion"] }
tokio = "1.28.2"
tracing = "0.1.37"
tower-http = { version = "0.4.0", features = ["fs"] }
tower-service = "0.3"
anyhow = "1.0.75"
