[package]
name = "korekto"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-runtime = "0.24.0"
shuttle-axum = "0.24.0"
shuttle-static-folder = "0.24.0"
axum = "0.6.18"
tokio = "1.28.2"
tracing = "0.1.37"
tower-http = { version = "0.4.0", features = ["fs"] }
tower-service = "0.3"
