name: 🚀 Deploy to Shuttle.rs
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: korekto/korekto-frontend
          ssh-key: ${{ secrets.KOREKTO_FRONTEND_DEPLOY_KEY }}
          path: target/front_git

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: target/front_git/package-lock.json

      - name: Build SPA
        run: (cd target/front_git && npm install && npm run build)

      - name: Prepare static content
        run: |
          mkdir static
          cp -a target/front_git/build/. static/
          cp -a welcome/. static/
          ls -al

      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          allow-dirty: 'true'
          no-test: 'true'
          secrets: |
            BASE_URL = 'https://korekto.shuttleapp.rs'
            FIRST_ADMIN = 'ledoyen'
            GITHUB_APP_ID = '${{ secrets.APP_GITHUB_APP_ID }}'
            GITHUB_APP_NAME = 'korekto'
            GITHUB_APP_CLIENT_ID = '${{ secrets.APP_GITHUB_APP_CLIENT_ID }}'
            GITHUB_APP_CLIENT_SECRET = '${{ secrets.APP_GITHUB_APP_CLIENT_SECRET }}'
            GITHUB_APP_PRIVATE_KEY = \"\"\"${{ secrets.APP_GITHUB_APP_PRIVATE_KEY }}\"\"\"
            GITHUB_APP_WEBHOOK_SECRET = '${{ secrets.APP_GITHUB_APP_WEBHOOK_SECRET }}'
            GITHUB_RUNNER_APP_ID = '${{ secrets.APP_GITHUB_RUNNER_APP_ID }}'
            GITHUB_RUNNER_APP_PRIVATE_KEY = \"\"\"${{ secrets.APP_GITHUB_RUNNER_APP_PRIVATE_KEY }}\"\"\"
            GITHUB_RUNNER_REPO_SLUG = 'lernejo/korekto-runner'
            GITHUB_RUNNER_INSTALLATION_ID = '${{ secrets.APP_GITHUB_RUNNER_INSTALLATION_ID }}'
