name: Deploy to Shuttle.rs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare static content
        run: |
          mkdir static
          cp -a welcome/. static/
          ls -al

      - uses: ledoyen/deploy-action@feature/idiomatic_secret_input
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          allow-dirty: "true"
          secrets: |
            COOKIE_SECRET_KEY = '${{ secrets.APP_COOKIE_SECRET_KEY }}'
